# A Simple Regression Case Study in R
#
# Fresh Foods Inc. owns several chains of supermarkets ranging from 
# discount/bulk  to specialty and organic food stores. They wish to examine 
# the effect of price per pound of ground beef, to weekly pounds of sales 
# per store. They have collected the prices from all their supermarkets 
# and the reported sales for the week that prices was in effect (in pounds). 
# The data are presented below. Assuming that there is a linear relationship 
# between sales (as the response variable) and price, we wish to estimate this 
# relationship.
# 
# This script runs regression analysis for data on file called
# "PriceAndSales.txt". Make sure to copy the file to your working
# directory. 
#
# To run this script, in R write: source("simpleRegression.r")
#
# We first read the file and put the contents on the "salePriceData" data
# frame. Notice, since the data in the file does not have headers we
# add these headers using col.name, which is set to a list of strings
# that are names of each column.
salePriceData <- read.table(
		"PriceAndSales.txt", col.name=c("Sales", "Price"))
cat("First let see if data is read properly\n")
cat("Hit return to see the data frame\n")
readline()
print(salePriceData)
cat("Hit return to continue:\n")
readline()

# first plot a scatter plot of the data relating Sales to price:
cat("Now plot the scatter plot of of the dependent and independent variables\n")
cat("Hit return to see the scatter plot:\n")
readline()
plot(salePriceData$Price, salePriceData$Sales,main="scatter plot")

# Now run the linear model (lm) function. The result is a structure that
# has many attributes. If you are curious run the command
# attributes(salePriceData.fit) to see all the information embedded in the result
# generated by lm function.
cat("results of the linear model are stored in \"salePriceData.fit\" variable\n")

salePriceData.fit<-lm(Sales ~  Price, data=salePriceData)

# summary function returns a useful summary of information about the
# fitted linear model 
cat("Hit return to see the summary information:\n")
readline()
print(summary(salePriceData.fit))
cat("Let us see what information is hidden in the fitted model\n")
cat("Hit return to see all attributes of fitted model\n")
readline()
print(attributes(salePriceData.fit))

# Now we wish to plot the regression line. The coefficients function of
# a fitted model (an object of type lm) returns a vector of coefficients
# with names equal to the name of variables plus an intercept. Thus we
# can extract bHat0 and bHatPrice (the estimated least squares
# coefficients):

bHat0 <- coefficients(salePriceData.fit)["(Intercept)"]
bHatPrice <- coefficients(salePriceData.fit)["Price"]

# Now use the lines function to add the plot of the line whose equation
# is  y= bHat0 + bHatPrice * x: First sort the values of the dependent
# variable (salePriceData$Price), this is the x values. Then apply bHat0+
# bHatPrice*x function to the sorted x values. This will give you the
# y-values. The lines functions gets the x-values and the y-values and
# draws a line connecting these values. The line then is added to the
# current plot. The optional col argument sets the color of the drawn
# line.
cat("Now add the regression line to the scatter plot\n")
cat("Hit return to see the regression line\n")
readline()
lines(sort(salePriceData$Price), bHat0+bHatPrice*sort(salePriceData$Price),col="blue")

# To check whether the assumption of normal errors is correct we plot the qq
# normal plot of the residuals 
cat("Hit return to see the normal-quantile plot of residuals")
readline()
qqnorm(salePriceData.fit$residuals)

# Unfortunately the lm function does not provide the confidence interval
# for the calculated coefficients. There is, however, an R function called
# confint that takes a structure of type lm and an optional variable
# confidence level (default alpha=.95) and returns a matrix giving upper and
# lower limits of confidence intervals for each estimated coefficient.
# Load the function confint and check its documentation for details.

cat("Hit return to see the confidence interval for coefficients\n")
readline()
bConfInt<-confint(salePriceData.fit)
cat("bConfInt:")
print(bConfInt)

# Now put the point estimate of bHat0 and bHatPrice on the plot
cat("Hit return to see the estimated bHat0 and bHatPrice:\n")
readline()
plot(coefficients(salePriceData.fit)["(Intercept)"],
      coefficients(salePriceData.fit)["Price"],, pch=19, col="red")

# Now add vertical and horizontal lines for confidence intervals for
# each coefficient individually

# first confidence interval for the intercept
cat("Hit return to see the confidence interval for Intercept:\n")
readline()
abline(v=bConfInt[1,],lty=1, col="blue")
cat("Hit return to see the confidence interval for Price:\n")
readline()
abline(h=bConfInt[2,],lty=1, col="violet")

# Now we wish to use our model for prediction. Thus, we have
# a set of new Price values and wish to predict the Sales for each new
# value. Point estimation is trivial: simply plug in the new Price in
# the regression equation: predictedSale= bHat0 + bHatPrice* newPrice
# However we are also interested in confidence intervals for our
# predictions. There are two kinds of confidence intervals: One is for
# prediction, that is given a specific value of Price give a 1-alpha
# confidence interval for the specific Sale. The other possibility is to ask 
# for a specific Price value what is the confidence interval for the "mean
# of predicted observations"? The function predict will calculate these
# values. 

# First come up with a bunch of new values
sortedPrice <- sort(salePriceData$Price) #sort the price values
len=length(sortedPrice)
av=(sortedPrice[len]+sortedPrice[len])/2; #the amount beyond largest Price
newPrice<-c(seq(0,sortedPrice[1],by=0.5), sortedPrice,
	seq(sortedPrice[len],sortedPrice[len]+av,by=0.5))
# Now calculate predicted values with confidence interval for a single
# observation. (Note that the predict function requires that the new
# values to be presented in a data frame format. Thus we cannot simply
# pass the newPrice vector to it. Instead we turn this vector into a
# data frame by: dat.frame(Price=newPrice). Also cbind(...)
# statement attaches the new Price values so they along with predicted
# and confidence intervals are printed.)
cat("Hit return to see intervals for single observations:\n")
readline()
salePriceData.new<-predict(salePriceData.fit, data.frame(Price=newPrice), interval="prediction")
print(cbind(data.frame(Price=newPrice),salePriceData.new))
# Now calculate predicted values (same as above) but with confidence
# interval for mean response
cat("Hit return to see the intervals for mean response:\n")
readline()
salePriceData.avg<-predict(salePriceData.fit, data.frame(Price=newPrice), interval="confidence")
print(cbind(data.frame(Price=newPrice),salePriceData.avg))
# We now plot the regression line and the prediction confidence interval
# lines:
cat("Hit return to see the regression line and single prediction intervals:\n")
readline()
matplot(newPrice,salePriceData.new, main="single prediction interval",type="l")
# Now plot the regression line and the mean response confidence interval
cat("Hit return to see the regression line and mean response prediction intervals:\n")
readline()
matplot(newPrice,salePriceData.avg, main="mean response prediction interval",type="l")
# Plot both intervals around the prediction line
cat("Hit return to see the regression line and both intervals:\n")
readline()
matplot(newPrice,cbind(salePriceData.avg, salePriceData.new),main="both intervals", type="l")
# Insert the original scatter plot
cat("Hit return to see regression line and both intervals along with the
original scatter plot:\n")
readline()
points(salePriceData$Price, salePriceData$Sales)


